# Generated by Django 4.1.7 on 2023-03-30 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('AccountNumber', models.CharField(max_length=25)),
                ('Id', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('IdType', models.IntegerField()),
                ('CommentCode', models.IntegerField()),
                ('TransferCode', models.IntegerField()),
                ('AdjustmentCode', models.IntegerField()),
                ('RegECode', models.IntegerField()),
                ('RegDCheckCode', models.IntegerField()),
                ('RegDTransferCode', models.IntegerField()),
                ('VoidCode', models.IntegerField()),
                ('SubActionCode', models.CharField(max_length=25)),
                ('SequenceNumber', models.IntegerField()),
                ('EffectiveDate', models.DateTimeField()),
                ('PostDate', models.DateTimeField()),
                ('PostTime', models.IntegerField()),
                ('PreviousAvailableBalance', models.DecimalField(decimal_places=2, max_digits=15)),
                ('UserNumber', models.IntegerField()),
                ('UserOverride', models.IntegerField()),
                ('SecurityLevels', models.IntegerField()),
                ('Description', models.CharField(max_length=25)),
                ('ActionCode', models.CharField(max_length=25)),
                ('SourceCode', models.CharField(max_length=25)),
                ('BalanceChange', models.DecimalField(decimal_places=2, max_digits=15)),
                ('InterestPenalty', models.DecimalField(decimal_places=2, max_digits=15)),
                ('NewBalance', models.DecimalField(decimal_places=2, max_digits=15)),
                ('FeeAmount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('EscrowAmount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('LastTranDate', models.DateTimeField()),
                ('MaturityLoanDueDate', models.DateTimeField(null=True)),
                ('Comment', models.CharField(max_length=25)),
                ('Branch', models.IntegerField()),
                ('ConsoleNumber', models.IntegerField()),
                ('BatchSequence', models.IntegerField()),
                ('SalesTaxAmount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('ActivityDate', models.DateTimeField()),
                ('BilledFeeAmount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('ProcessorUser', models.IntegerField()),
                ('MemberBranch', models.CharField(max_length=25)),
                ('SubSourceCode', models.IntegerField()),
                ('ConfirmationSequence', models.IntegerField()),
                ('MicrAccountNumber', models.CharField(max_length=25)),
                ('MicrRtNumber', models.CharField(max_length=25)),
                ('Recurring', models.IntegerField()),
                ('FeeExemptCourtesyAmount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('BalSeg001SegmentId', models.CharField(max_length=25)),
                ('BalSeg001PmtChangeDate', models.DateTimeField(null=True)),
                ('InterestEffectiveDate', models.DateTimeField(null=True)),
                ('BalSeg001PrevFirstPmtDate', models.DateTimeField(null=True)),
                ('DraftNumber', models.CharField(max_length=25)),
                ('TracerNumber', models.CharField(max_length=25)),
                ('SubSourceDescription', models.CharField(max_length=25)),
                ('TransactionAmount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('ConfirmationNumber', models.CharField(max_length=25)),
            ],
        ),
    ]
