from django.db import models

# Create your models here.


class Entry(models.Model):
    AccountNumber = models.CharField(max_length=25)
    Id = models.CharField(max_length=25, primary_key=True)
    IdType = models.IntegerField()
    CommentCode = models.IntegerField()
    TransferCode = models.IntegerField()
    AdjustmentCode = models.IntegerField()
    RegECode = models.IntegerField()
    RegDCheckCode = models.IntegerField()
    RegDTransferCode = models.IntegerField()
    VoidCode = models.IntegerField()
    SubActionCode = models.CharField(max_length=25)
    SequenceNumber = models.IntegerField()
    EffectiveDate = models.DateTimeField()
    PostDate = models.DateTimeField()
    PostTime = models.IntegerField()
    PreviousAvailableBalance = models.DecimalField(max_digits=15, decimal_places=2)
    UserNumber = models.IntegerField()
    UserOverride = models.IntegerField()
    SecurityLevels = models.IntegerField()
    Description = models.CharField(max_length=25)
    ActionCode = models.CharField(max_length=25)
    SourceCode = models.CharField(max_length=25)
    BalanceChange = models.DecimalField(max_digits=15, decimal_places=2)
    InterestPenalty = models.DecimalField(max_digits=15, decimal_places=2)
    NewBalance = models.DecimalField(max_digits=15, decimal_places=2)
    FeeAmount = models.DecimalField(max_digits=15, decimal_places=2)
    EscrowAmount = models.DecimalField(max_digits=15, decimal_places=2)
    LastTranDate = models.DateTimeField()
    MaturityLoanDueDate = models.DateTimeField(null = True)
    Comment = models.CharField(max_length=25)
    Branch = models.IntegerField()
    ConsoleNumber = models.IntegerField()
    BatchSequence = models.IntegerField()
    SalesTaxAmount = models.DecimalField(max_digits=15, decimal_places=2)
    ActivityDate = models.DateTimeField()
    BilledFeeAmount = models.DecimalField(max_digits=15, decimal_places=2)
    ProcessorUser = models.IntegerField()
    MemberBranch = models.CharField(max_length=25)
    SubSourceCode = models.IntegerField()
    ConfirmationSequence = models.IntegerField()
    MicrAccountNumber = models.CharField(max_length=25)
    MicrRtNumber = models.CharField(max_length=25)
    Recurring = models.IntegerField()
    FeeExemptCourtesyAmount = models.DecimalField(max_digits=15, decimal_places=2)
    BalSeg001SegmentId = models.CharField(max_length=25)
    BalSeg001PmtChangeDate = models.DateTimeField(null = True)
    InterestEffectiveDate = models.DateTimeField(null = True)
    BalSeg001PrevFirstPmtDate = models.DateTimeField(null = True)
    DraftNumber = models.CharField(max_length=25)
    TracerNumber = models.CharField(max_length=25)
    SubSourceDescription = models.CharField(max_length=25)
    TransactionAmount = models.DecimalField(max_digits=15, decimal_places=2)
    ConfirmationNumber = models.CharField(max_length=25)